# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and synced from /etc/nixos to kryonix for host inspiron.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4eaa3f1e-87cd-4fb2-861a-e0931fc23753";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4eaa3f1e-87cd-4fb2-861a-e0931fc23753";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/4eaa3f1e-87cd-4fb2-861a-e0931fc23753";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8A90-591D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fddd52bf-66d0-43aa-80d6-0bbfeba386a8"; }
    ];

  # Ativação do pool ZFS secundário Kryonix-HPOOL no sda1 preservando dados
  fileSystems."/mnt/storage" = {
    device = "Kryonix-HPOOL/home";
    fsType = "zfs";
    options = [ "nofail" ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
